version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - /var/lib/mysql

  wp:
    image: wordpress:php7.0-apache
    depends_on: 
      - db
    ports:
      - 80:80
    volumes:
      - /var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress

